{% set version = '0.0.7' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-dssat
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/DSSAT_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/DSSAT/DSSAT_{{ version }}.tar.gz
  sha256: d06181d2458854067511d1d5d0f6ceb6e66ff2c46555eddf1c047bf7d32e5da0

build:
  merge_build_host: True  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dplyr >=1.0.0
    - r-glue
    - r-lubridate
    - r-magrittr
    - r-purrr
    - r-readr
    - r-rlang
    - r-stringr
    - r-testthat >=3.0.0
    - r-tibble
    - r-tidyr
    - r-tidyselect
  run:
    - r-base
    - r-dplyr >=1.0.0
    - r-glue
    - r-lubridate
    - r-magrittr
    - r-purrr
    - r-readr
    - r-rlang
    - r-stringr
    - r-testthat >=3.0.0
    - r-tibble
    - r-tidyr
    - r-tidyselect

test:
  commands:
    - $R -e "library('DSSAT')"           # [not win]
    - "\"%R%\" -e \"library('DSSAT')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=DSSAT
  license: GPL-3.0-or-later
  summary: The purpose of this package is to provide a comprehensive R interface to the Decision
    Support System for Agrotechnology Transfer Cropping Systems Model (DSSAT-CSM; see
    <https://dssat.net> for more information). The package provides cross-platform functions
    to read and write input files, run DSSAT-CSM, and read output files.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - palderman

# Package: DSSAT
# Type: Package
# Title: A Comprehensive R Interface for the DSSAT Cropping Systems Model
# Version: 0.0.7
# Date: 2023-03-27
# Author: Phillip D. Alderman [aut, cre]
# Maintainer: Phillip D. Alderman <phillip.alderman@okstate.edu>
# Description: The purpose of this package is to provide a comprehensive R interface to the Decision Support System for Agrotechnology Transfer Cropping Systems Model (DSSAT-CSM; see <https://dssat.net> for more information). The package provides cross-platform functions to read and write input files, run DSSAT-CSM, and read output files.
# License: GPL (>= 3)
# Encoding: UTF-8
# Imports: dplyr (>= 1.0.0), glue, lubridate, magrittr, methods, purrr, readr, rlang, stringr, testthat (>= 3.0.0), tibble, tidyr, tidyselect, utils
# RoxygenNote: 7.2.3
# Suggests: knitr, rmarkdown
# BugReports: https://github.com/palderman/DSSAT/issues
# Config/testthat/edition: 3
# NeedsCompilation: no
# Packaged: 2023-03-27 17:14:49 UTC; palderman
# Repository: CRAN
# Date/Publication: 2023-03-28 00:00:02 UTC
